### ISSUE TITLE
Crashing instantly on launch.

### ISSUE THREAD

**Issue by Seristic** [tom5454/ViveCraftCompat#1]
I am unsure of what I have changed, but when this mod is enabled on its own (with it's required mods ofc) it seems to crash EVERY time now. Would this be summin I can do to fix this?

**Comment by JadianRadiator** [comment]
the person who made it has it set up requiring this [Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium)... which isn't available for 1.19

**Comment by Seristic** [comment]
I've been using 1.19.2 and it was working last week. What could've changed from then?

**Comment by JadianRadiator** [comment]
> The mod was built with ViveCraft version `0.0.15` the latest ViveCraft version has an almost full rewrite so I have to port ViveCraftCompat to this new version.

that doesn't address the fact that you coded a 1.16.x only mod as a dependency of a 1.19.x mod

**Comment by tom5454** [comment]
Sodium is for fabric and is only available on [Modrinth](https://modrinth.com/mod/sodium) for any other Minecraft version.
I use Rubidium which is the forge port of Sodium, but it's not a required dependency for this mod. Sodium/Rubidium offers better performance with VR (for me at least).

**Comment by JadianRadiator** [comment]
it crashes the game when it doesn't see Sodium installed

**Comment by JadianRadiator** [comment]
It's still crashing and I don't know why.
There is no crash log, just the regular log.

Here's a pastebin of the log.
https://pastebin.com/AksdpaEL
And the CurseForge profile of what mods I'm using.
[Dwarven Earthmaw.zip](https://github.com/tom5454/ViveCraftCompat/files/12307683/Dwarven.Earthmaw.zip)

**Comment by Seristic** [comment]
Yea, I contacted Tom at CF and forgot to post back here. Gonna close this. Thank you both!
