### ISSUE TITLE
Fabric 1.20.4?

### ISSUE THREAD

**Issue by RafaelOfDarkness** [tom5454/ViveCraftCompat#12]
Vivecraft compat is not updated for Fabric 1.20.4, i want to know when it will come because i would love to use vivecraft and first person together.

Thanks for attention

**Comment by tom5454** [comment]
Done

**Comment by RafaelOfDarkness** [comment]
thank you


Em dom., 2 de jun. de 2024 às 12:07, tom5454 ***@***.***>
escreveu:
