### ISSUE TITLE
Create Needed

### ISSUE THREAD

**Issue by ResoluteRug3471** [tom5454/ViveCraftCompat#13]
You have to have the create mod if you want to launch it at all. I was just trying to use it with JourneyMap only, but when I tried it, it said I had to have the create mod installed.

**Comment by ajaxnotmeta** [comment]
also needed custom player model on forge for some reason even though i just want to use Create compat only

**Comment by tom5454** [comment]
The fabric version only has the create compat, so create is needed.
The forge version uses CPM's GUI and config frameworks.
