### ISSUE TITLE
Fabric 1.20.1 Requires Create

### ISSUE THREAD

**Issue by M4j0d1** [tom5454/ViveCraftCompat#14]
When I First Used the Vivecraft compat Mod the game crashed,
After checking the logs it says that the mod requires any version of Create,
Upon installing Create it started working, 
This shouldn't happen as Create is listed as a Optional Mod instead of a Required Mod,
This Is Annoying Because I Don't want to use Create It Makes me Remove My Favorite Mod And It Adds A lot Of Stuff. 
![IMG_20240530_162952](https://github.com/tom5454/ViveCraftCompat/assets/171257074/9fcda56a-1d7e-43ca-82c2-9d32142f9f10)

**Comment by tom5454** [comment]
Latest version removes the Create requirement
