### ISSUE TITLE
Journeymap minimap cant be repositioned

### ISSUE THREAD

**Issue by BlankSBG** [tom5454/ViveCraftCompat#15]
neoforge 1.20.1
vivecraft compat 1.20-1.3.4
journeymaps 5.9.23-forge
the red outline disappears when i add the journeymaps element to an overlay, but the jade element works just fine. ive tried different versions of journeymaps and this mod and i havent gotten it to work, ive also tried it on the same overlay and two seperate overlays

**Comment by tom5454** [comment]
It looks like either a journeymap or a vivecraft update broke the minimap overlay.

**Comment by StarleetTW** [comment]
> It looks like either a journeymap or a vivecraft update broke the minimap overlay.

Help us find the right version of mods
