### ISSUE TITLE
1.21 Support?

### ISSUE THREAD

**Issue by Silk-OT** [tom5454/ViveCraftCompat#16]
Hello I would like to know if 1.21 support is planned or being developed as this mod seems extremely helpful, as it makes many fun and useful mods more compatible.

**Comment by Silk-OT** [comment]
Thank you for updating your mod, I really appreciate it ^~^

Is fabric support going to continue or is Forge the only version planned as of 1.21 and onward? Thank you

**Comment by tom5454** [comment]
The fabric version doesn't have anything right now for 1.21.
ViveCraft fixed all of the compatibility issues this mod provided patches for on 1.21.
When create releases I'll port the Create compat to fabric.
