### ISSUE TITLE
Open the overlays menu from the pause menu and create a new overlay and add JourneyMap to it. Then position it on your right hand.

### ISSUE THREAD

**Issue by StarleetTW** [tom5454/ViveCraftCompat#20]
Open the overlays menu from the pause menu and create a new overlay and add JourneyMap to it. Then position it on your right hand.

_Originally posted by @tom5454 in https://github.com/tom5454/ViveCraftCompat/issues/18#issuecomment-2296411674_

It doesn't work
https://www.youtube.com/watch?v=wqBF4l7_dUk

**Comment by StarleetTW** [comment]
dont ignore pls

**Comment by tom5454** [comment]
Duplicate of #15
