### ISSUE TITLE
Please Port ViveCraftCompat to 1.21.x for Fabric

### ISSUE THREAD

**Issue by Nafum24** [tom5454/ViveCraftCompat#22]
Hi! 
Pretty much as the title says I can only find the 1.21 port for neoforge but not for fabric. Do you have plans to bring this mod over for fabric 1.21? 

Thank you, have a good one!

**Comment by tom5454** [comment]
The fabric version doesn't have anything right now for 1.21.
ViveCraft or the base mods fixed all of the compatibility issues this mod provided patches for on 1.21.
When Create releases then I'll release a port of the Create compat on fabric.
The overlay system relies on a specific Forge/NeoForge api that isn't available on fabric and would require a lot of patches to port.

**Comment by Nafum24** [comment]
oh okay interesting, I'll test it out again but when I gave it a go without the compat installed I couldn't get the vanilla hands to disappear so I just had these big ole hands in my screen with oversized tools as well. I tried all the different settings in the first person mod. I'll mess with it again,  maybe I need to update my vivecraft or VRapi. 

Thanks for the wuick response!
