### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Rainee4563** [tom5454/ViveCraftCompat#3]
Crash on startup seems like mixins error

https://mclo.gs/ECZBnZI

**Comment by tom5454** [comment]
You are missing a mod:
```
Missing or unsupported mandatory dependencies:
	Mod ID: 'tofucraft', Requested by: 'maturidelight', Expected range: '[1.20.1-5.2.4.1,)', Actual version: '[MISSING]'
```
Which blocks vivecraft from loading, that causes the mixin error (it mixins into vivecraft code, that's not there).
