### ISSUE TITLE
No Strartup

### ISSUE THREAD

**Issue by bdveeder** [tom5454/ViveCraftCompat#4]
After Installing this mod the game will no longer start. After opening up the Launcher and clicking 'Play' the launcher closes like it is going to load the game. But after waiting for some time, I even attempted to let it try and load overnight for 12+ hrs the game never loads onto the Mojang screen. Checking the task manager shows that the OpenJDK Library Platform binary is running but at 0% CPU. The game never crashes and when I close it there isn't any crash report being generated. So I'm not entirely sure what the issue is. I am using my own modpack on Curseforge (BaileyDrew's Lowtech). The ViveCraft Compat mod solves a lot of the niche issues with running modded Minecraft on Vivecraft, So I'd really like to be able to use it! Thanks!

**Comment by SHXRKIIE** [comment]
Its because of the new Vivecraft update, tom has to make it compatible
