### ISSUE TITLE
Overlay items unlock

### ISSUE THREAD

**Issue by RedSkul1** [tom5454/ViveCraftCompat#5]
Everytime I press the pause button it instead unlocks all of my custom overlays.

**Comment by tom5454** [comment]
What minecraft version are you using?

**Comment by RedSkul1** [comment]
I am using 1.19.2

**Comment by RedSkul1** [comment]
Any news on this?
I am using a modpack with 71 other mods, but I dont think they would have any effect on this.

**Comment by tom5454** [comment]
You move overlays by clicking the `L` or `R` button then pressing the menu button to release.
This issue only happens if you press both of the move buttons. (in my testing)

**Comment by RedSkul1** [comment]
I switch between the 2 yes, but that is only to move it back over from
chucking itself so far away, then when I get it in place I lock it to the
left controller.  it is only when I am in the game and and able to play, I
press the pause button but instead of pausing it throws my journeymap way
ahead and to the left and it follows my hmd "If I press pause again it will
actually pause" but if I go back into the menu and check the overlay it
says no lock.
