### ISSUE TITLE
Can't launch the mod

### ISSUE THREAD

**Issue by 3zekielZorr** [tom5454/ViveCraftCompat#9]
Hey, i'm using the fabric 1.20.1 version of the mod on a client side only modpack that does not contain Create mod. But when i'm launching MC, fabric warn me that i need Create to run the Vivecraft Compat mod...

I just want to use it with journeymap and jade

**Comment by tom5454** [comment]
The fabric version only has the create patches, you have to use Forge for the overlay system.
